# Site Settings
title: 竹北國小 | iEarn計劃展示廳
email: 185thjh@gmail.com
description: 竹北國小iEarn測試計劃.
baseurl: "/jekflix-template" # the subpath of your site, e.g. /blog
url: "http://www.cbes.hcc.edu.tw/bin/home.php" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: 竹北國小185英專役男
user_description: yoloswag.
disqus_username: disqus_username

# Social Media
# Remove the item if you don't need it
#github_username: github_username
facebook_username: facebook_username
#twitter_username: twitter_username
#instagram_username: instagram_username
#linkedin_username: linkedin_username
#medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
